### ISSUE TITLE
No Compatible RT Patch for this kernel version(5.4.181)

### ISSUE THREAD

**Issue by BoltzmannZhaung** [OpenNuvoton/MA35D1_linux-5.4.y#1]
the current MA35D1_linux version is 5.4.181, and there's no compatible RT patch for this version (from RT patch site https://cdn.kernel.org/pub/linux/kernel/projects/rt/5.4).
will version be update to 5.4.182 or 5.4.209 ?

**Comment by ychuang3** [comment]
Hi,

I made the patch from 5.4.181 -> 5.4.182. 
# git am ../patch_182/*.patch
[patch_182.tar.gz](https://github.com/OpenNuvoton/MA35D1_linux-5.4.y/files/9493299/patch_182.tar.gz)

Then, you can update the 5.4.181 to 5.4.182. Just for RT pacth test.
Note that it can result in kernel modules failed to inseted due to version check.

YC

**Comment by BoltzmannZhaung** [comment]
Eh.... Have you test this patch?
Actually I have update kernel version to 5.4.1 82 previously by myself, then merged the RT patch. But there is a error occurred that is same to updating kernel version by your patch_182.tar.gz file.
This error will be reported when compile kernel specifically setting kernel to Fully Preemptible Kernel (Real-Time).If you check the compiling log, the error is located in spinlock_types_rt.h and associated to SPI driver. 
I fixed it, but I doubt it’s safety. Is there a official solution?

**Comment by ychuang3** [comment]
Since Nuvoton FAE is already working on your question, we will not discuss this topic further here.

**Comment by BoltzmannZhaung** [comment]
Thank you
